<?php

        PG_Blocks::register_block_type( array(
            'name' => 'mossco-fse/cafe-menu-right-col',
            'supports' => array('color' => array('background' => false,'text' => false,'gradients' => false,'link' => false,),'typography' => array('fontSize' => false,),'anchor' => false,'align' => false,),
            'base_url' => get_template_directory_uri(),
            'base_path' => get_template_directory(),
            'js_file' => 'blocks/cafe-menu-right-col/cafe-menu-right-col.js',
            'attributes' => array(
                'cafe_menu_right_col' => array(
                    'type' => 'text',
                    'default' => '<h4 class="border-b-2 border-primary-NORMAL border-solid font-sans py-2 text-Mossco-grey-semi text-xl uppercase md:mt-0">Sweet pastries and cakes</h4> <p class="caption pb-12 pt-6">Selection of the items noted below available daily from 10am serviced from the bar. <br>Take out or eat in.</p> <div class="border-r-4 border-t-4 dark border-primary-NORMAL rounded-xl"> <h4 class="border-b-2 border-primary-NORMAL border-solid font-sans my-6 pb-3 text-Mossco-grey-semi text-xl uppercase">Morning</h4> <div class="menu_item"> <dd>Selection of Danish pastries, Croissants and Pain Chocolate</dd> <p class="allergen_info">(1)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Fresh Scones</dd> <p class="allergen_info">(10,4)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Portuguese custard tarts</dd> <p class="allergen_info">(4)</p> <p class="price">€ 3.50</p> </div> </div> <div class="border-r-4 border-t-4 dark rounded-xl border-primary-NORMAL second mt-10"> <h4 class="border-b-2 border-primary-NORMAL border-solid font-sans my-6 pb-3 text-Mossco-grey-semi text-xl uppercase">Afternoon</h4> <div class="menu_item"> <dd>Carrot cake</dd> <p class="allergen_info">(2,6)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Madeira sponge</dd> <p class="allergen_info">(11,14)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Brownies &amp; blondies</dd> <p class="allergen_info">(2)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Orange polenta cake</dd> <p class="allergen_info">(14)</p> <p class="price">€ 3.50</p> </div> </div> <div data-empty-placeholder class="cafe-menu-bg h-0"></div>'
                )
            ),
            'example' => array(
'cafe_menu_right_col' => '<h4 class="border-b-2 border-primary-NORMAL border-solid font-sans py-2 text-Mossco-grey-semi text-xl uppercase md:mt-0">Sweet pastries and cakes</h4> <p class="caption pb-12 pt-6">Selection of the items noted below available daily from 10am serviced from the bar. <br>Take out or eat in.</p> <div class="border-r-4 border-t-4 dark border-primary-NORMAL rounded-xl"> <h4 class="border-b-2 border-primary-NORMAL border-solid font-sans my-6 pb-3 text-Mossco-grey-semi text-xl uppercase">Morning</h4> <div class="menu_item"> <dd>Selection of Danish pastries, Croissants and Pain Chocolate</dd> <p class="allergen_info">(1)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Fresh Scones</dd> <p class="allergen_info">(10,4)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Portuguese custard tarts</dd> <p class="allergen_info">(4)</p> <p class="price">€ 3.50</p> </div> </div> <div class="border-r-4 border-t-4 dark rounded-xl border-primary-NORMAL second mt-10"> <h4 class="border-b-2 border-primary-NORMAL border-solid font-sans my-6 pb-3 text-Mossco-grey-semi text-xl uppercase">Afternoon</h4> <div class="menu_item"> <dd>Carrot cake</dd> <p class="allergen_info">(2,6)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Madeira sponge</dd> <p class="allergen_info">(11,14)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Brownies &amp; blondies</dd> <p class="allergen_info">(2)</p> <p class="price">€ 3.50</p> </div> <div class="menu_item"> <dd>Orange polenta cake</dd> <p class="allergen_info">(14)</p> <p class="price">€ 3.50</p> </div> </div> <div data-empty-placeholder class="cafe-menu-bg h-0"></div>'
            ),
            'dynamic' => false,
            'version' => '1.0.234'
        ) );
